name: Bug Report / 问题报告
description: Report a bug to help us improve / 报告 Bug 帮助我们改进
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! / 感谢你花时间填写这个 Bug 报告！

  - type: textarea
    id: description
    attributes:
      label: Bug Description / 问题描述
      description: A clear and concise description of what the bug is. / 清晰简洁地描述问题是什么。
      placeholder: Describe the bug... / 描述这个 bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce / 复现步骤
      description: Steps to reproduce the behavior. / 复现问题的步骤。
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior / 预期行为
      description: What you expected to happen. / 你期望发生什么。
      placeholder: What should happen... / 应该发生什么...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / 实际行为
      description: What actually happened. / 实际发生了什么。
      placeholder: What actually happened... / 实际发生了什么...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / 截图
      description: If applicable, add screenshots to help explain your problem. / 如果适用，添加截图来帮助解释你的问题。
      placeholder: Drag and drop images here... / 拖拽图片到这里...

  - type: dropdown
    id: browser
    attributes:
      label: Browser / 浏览器
      description: What browser are you using? / 你使用的是什么浏览器？
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System / 操作系统
      description: What OS are you using? / 你使用的是什么操作系统？
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04

  - type: dropdown
    id: ai-provider
    attributes:
      label: AI Provider / AI 服务商
      description: Which AI provider are you using? / 你使用的是哪个 AI 服务商？
      options:
        - OpenAI
        - DeepSeek
        - Volcengine (Doubao)
        - Zhipu AI
        - Kimi
        - Anthropic (Claude)
        - OpenRouter
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / 其他信息
      description: Any other context about the problem. / 关于这个问题的其他信息。
      placeholder: Add any other context... / 添加其他相关信息...
